name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - run: pip install -r requirements.txt

    - run: python scripts/train.py

    - uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: app/artifacts/**


  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: app/artifacts

    - run: |
        sudo apt-get update
        sudo apt-get install -y jq bc

    - name: Compare metrics
      run: |
        CUR_R2=$(jq .r2 app/artifacts/metrics.json)
        BEST_R2=${{ vars.BEST_R2 }}

        echo "Current R2: $CUR_R2"
        echo "Best R2: $BEST_R2"

        if (( $(echo "$CUR_R2 <= $BEST_R2" | bc -l) )); then
          echo "2022BCD0039 ---- Metric did not improve"
          exit 0
        fi

        echo "New best model found"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t sibykannabcd39/wine_predict_2022bcd0039:latest .
        docker push sibykannabcd39/wine_predict_2022bcd0039:latest
